---
abstract: 'Perl module of Thrift'
author:
  - 'Developers Mailing List <thrift-dev@incubator.apache.org>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110930'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Thrift
requires:
  Bit::Vector: 0
  Encode: 0
  HTTP::Request: 0
  IO::Select: 0
  IO::Socket::INET: 0
  IO::String: 0
  LWP::UserAgent: 0
  POSIX: 0
  constant: 0
  perl: 5.6.0
  utf8: 0
version: 0.6.1_01
